// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eihgfuxgusrezciuaosq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVpaGdmdXhndXNyZXpjaXVhb3NxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY1MDEzOTIsImV4cCI6MjA3MjA3NzM5Mn0.PzbfJcdAFQIn02i6NNHYbcu6exlZqesiyuxV8476Dyk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});